2021-11-29 15:54:57,385 - trainer.py[line:25] - INFO: Running with identifier 20211129_155457
2021-11-29 15:54:57,385 - trainer.py[line:27] - INFO: Saving log to log\cifar10\20211129_155457\run.log
2021-11-29 15:54:57,385 - trainer.py[line:28] - INFO: Using args: [('log_name', 'cifar10'), ('data_train', 'dataset/cifar_10_train'), ('data_eval', 'dataset/cifar_10_test'), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 1), ('log_dir', 'log'), ('tf_dir', 'tensorboard'), ('output_dir', 'output'), ('not_ignore_warning', False), ('enable_tensorboard', True)]
2021-11-29 15:54:57,387 - trainer.py[line:39] - INFO: Using tensorboard, store at: tensorboard\cifar10\20211129_155457
2021-11-29 15:54:57,387 - train.py[line:93] - INFO: Running model resnet50
2021-11-29 15:55:06,929 - trainer.py[line:49] - ERROR: Multi images detected!
