2021-11-28 21:26:39,813 - main.py[line:24] - INFO: Running with identifier 20211128_212639
2021-11-28 21:26:39,813 - main.py[line:26] - INFO: Saving log to log\cifar10\20211128_212639\run.log
2021-11-28 21:27:36,781 - main.py[line:38] - ERROR: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\collate.py", line 86, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.Image.Image'>

