2021-11-29 16:06:36,588 - trainer.py[line:25] - INFO: Running with identifier 20211129_160636
2021-11-29 16:06:36,588 - trainer.py[line:27] - INFO: Saving log to log\cifar10\20211129_160636\run.log
2021-11-29 16:06:36,588 - trainer.py[line:28] - INFO: Using args: [('log_name', 'cifar10'), ('data_train', 'dataset/cifar_10_train'), ('data_eval', 'dataset/cifar_10_test'), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 1), ('log_dir', 'log'), ('tf_dir', 'tensorboard'), ('output_dir', 'output'), ('not_ignore_warning', False), ('enable_tensorboard', True)]
2021-11-29 16:06:36,591 - trainer.py[line:39] - INFO: Using tensorboard, store at: tensorboard\cifar10\20211129_160636
2021-11-29 16:06:36,591 - train.py[line:96] - INFO: Running model resnet50
2021-11-29 16:06:44,721 - trainer.py[line:49] - ERROR: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\lzl32947\anaconda3\envs\pytorch190\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "K:\Program\Pycharm\ALiProject\functional\datasets\mixup_dataset.py", line 43, in __getitem__
    image = image * alpha + self.images[other] * (1 - alpha)
TypeError: unsupported operand type(s) for *: 'Image' and 'float'

